<a href="https://colab.research.google.com/github/codebytemirza/ML_practices/blob/main/numpy_ML_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **How to install numpy**

In [2]:
!pip install numpy

# **How to import numpy**


In [3]:
import numpy as np

# **Create the numpy array**


1.   1 dimensional Array
2.   2 dimensional Array



In [4]:
#one diemnsional array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
#two dimensional array
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


# **Check Dimensions of np array**

In [6]:
a.ndim  #as it is one dimensional array

1

In [7]:
b.ndim #as it is two dimensional array

2

# **Check size of np array**


> it shows how much elements are there in a matrix


In [8]:
a.size #it shows how much elements are there in a matrix

5

In [9]:
b.size

8

# **Shape of the np matrix**


> rows and columns in a matrix



In [10]:
a.shape #it shows rows and columns in a matrix

(5,)

In [12]:
b.shape

(2, 4)

# **Check Data Type of np array**


> it shows which type of data inside the array



In [13]:
a.dtype #it shows which type of data inside the array

dtype('int64')

In [14]:
b.dtype

dtype('int64')

# **Create Ones**

In [16]:
mx_1s = np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


**Want to change the dtype data type**

In [21]:
mx_1s = mx_1s.astype(int)

**Check data type**

In [22]:
mx_1s.dtype

dtype('int64')

**Create n dimensional ones array**

In [23]:
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# **Create Zeros**

In [24]:
mx_os = np.zeros((3,4))
print(mx_os)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# **Empty Array**

In [25]:
mx_emp = np.empty((3,3))
print(mx_emp)

[[4.68164088e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


# **np array functions**

**arrange**

In [38]:
mx_1d = np.arange(1,13,1) #this function will make an ordered array from starting to end-1
print(mx_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**linspace**

In [45]:
mx_1d = np.linspace(1,13,4) #this function will make an ordered array from starting to end-1
print(mx_1d)

[ 1.  5.  9. 13.]


**reshape**

In [46]:
mx_1d = mx_1d.reshape(2,2)
print(mx_1d)

[[ 1.  5.]
 [ 9. 13.]]


**ravel**

In [53]:
mx_1d = np.ones((2,2))
print(mx_1d)

[[1. 1.]
 [1. 1.]]


In [52]:
mx_1d = mx_1d.ravel()
print(mx_1d)

[1. 1. 1. 1.]


**flattern**

In [54]:
mx_1d = mx_1d.flatten()
print(mx_1d)

[1. 1. 1. 1.]


**Transpose**

In [56]:
mx_nd = np.empty((2,3))
print(mx_nd)

[[4.9e-324 1.5e-323 2.5e-323]
 [3.5e-323 4.4e-323 5.4e-323]]


In [57]:
mx_nd = mx_nd.transpose()
print(mx_nd)

[[4.9e-324 3.5e-323]
 [1.5e-323 4.4e-323]
 [2.5e-323 5.4e-323]]
